# Generated by Django 5.0.6 on 2024-06-15 20:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_producto_stock_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
