# Generated by Django 5.0.6 on 2024-06-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producto_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
    ]
