# Generated by Django 5.0.6 on 2024-05-19 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.CharField(max_length=50)),
                ('session_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('card_number', models.CharField(max_length=4)),
                ('accounting_date', models.CharField(max_length=10)),
                ('transaction_date', models.DateTimeField()),
                ('authorization_code', models.CharField(max_length=10)),
                ('payment_type_code', models.CharField(max_length=10)),
                ('response_code', models.IntegerField()),
                ('installments_number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
