# Generated by Django 5.0.6 on 2024-06-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_transaccion_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='transaction_date',
            field=models.CharField(max_length=50),
        ),
    ]
