# Generated by Django 5.0.6 on 2024-06-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_comuna_provincia_region_remove_direccion_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sucursal', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=100)),
                ('num_direccion', models.IntegerField()),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='compra.comuna')),
            ],
        ),
    ]
