# Generated by Django 5.0.6 on 2024-06-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_carro_carroitem_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='precio',
        ),
    ]
