# Generated by Django 5.0.6 on 2024-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0008_remove_orderitem_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_estado', models.CharField(max_length=30)),
            ],
        ),
    ]
