# Generated by Django 5.0.6 on 2024-06-28 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0009_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compra.estado'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.transaccion'),
        ),
    ]
