# Generated by Django 5.0.6 on 2024-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0010_order_estado_order_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
